create or replace PROCEDURE xxnbty_inv_onhand_load( X_Errbuf OUT VARCHAR2,
   X_Retcode OUT VARCHAR2)
AS   
BEGIN

INSERT
INTO MTL_TRANSACTIONS_INTERFACE
  (
    TRANSACTION_UOM,
    TRANSACTION_DATE,
    SOURCE_CODE,  
    SOURCE_LINE_ID,
    SOURCE_HEADER_ID,
    PROCESS_FLAG,
    TRANSACTION_MODE,
    LOCK_FLAG,
    LAST_UPDATE_DATE,
    LAST_UPDATED_BY,
    CREATION_DATE,
    CREATED_BY,
    ITEM_SEGMENT1,
    SUBINVENTORY_CODE,
    ORGANIZATION_ID ,
    TRANSACTION_QUANTITY,
    PRIMARY_QUANTITY,
    TRANSACTION_TYPE_ID,
    DST_SEGMENT1,
    DST_SEGMENT2,
    DST_SEGMENT3,
    DST_SEGMENT4,
    DST_SEGMENT5,
    DST_SEGMENT6,
    DST_SEGMENT7,
    DST_SEGMENT8,
    TRANSACTION_INTERFACE_ID,
    ATTRIBUTE1
  )
SELECT TRANSACTION_UOM,
  TRANSACTION_DATE,
  SOURCE_CODE,
  SOURCE_LINE_ID,
  SOURCE_HEADER_ID,
  PROCESS_FLAG,
  TRANSACTION_MODE,
  LOCK_FLAG,
  LAST_UPDATE_DATE,
  LAST_UPDATED_BY,
  CREATION_DATE,
  CREATED_BY,
  ITEM_SEGMENT1,
  SUBINVENTORY_CODE,
  ORGANIZATION_ID ,
  TRANSACTION_QUANTITY,
  PRIMARY_QUANTITY,
  TRANSACTION_TYPE_ID,
  DST_SEGMENT1,
  DST_SEGMENT2,
  DST_SEGMENT3,
  DST_SEGMENT4,
  DST_SEGMENT5,
  DST_SEGMENT6,
  DST_SEGMENT7,
  DST_SEGMENT8,
  TRANSACTION_INTERFACE_ID,
  ATTRIBUTE1
FROM XXNBTY_MTL_TRX_IFACE_STAGE;

commit;
X_Retcode := 0;

EXCEPTION
   WHEN OTHERS
   THEN
      X_Errbuf := SUBSTR (SQLERRM, 1, 100);
      
      X_Retcode := 2;
END;